<?php
/** Dedicated staff manager for ongoing ministries. */
if (!defined('ABSPATH')) { exit; }

function surfside_tools_staff_ministries_manager_shortcode() {
    if (function_exists('surfside_tools_prevent_cache')) surfside_tools_prevent_cache();
    if (function_exists('surfside_tools_staff_enqueue_styles')) surfside_tools_staff_enqueue_styles();
    if (function_exists('surfside_tools_site_information_manager_assets')) surfside_tools_site_information_manager_assets();
    if (!is_user_logged_in()) return function_exists('surfside_tools_staff_login_box') ? surfside_tools_staff_login_box('Please log in to manage ministries.') : '<p>Please log in.</p>';
    if (!current_user_can('manage_options')) return '<div class="surfside-staff-shell"><p>You do not have permission to manage ministries.</p></div>';

    $notice='';
    if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST' && isset($_POST['surfside_ministries_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['surfside_ministries_nonce'])),'surfside_ministries_save')) {
        $posted=isset($_POST['ministries']) && is_array($_POST['ministries']) ? wp_unslash($_POST['ministries']) : array();
        surfside_tools_update_ministries($posted);
        $notice='<div class="surfside-mobile-notice">Ministries saved.</div>';
    }

    $ministries=surfside_tools_get_ministries();
    $audiences=surfside_tools_ministry_audience_choices();
    $icon_choices=array(
        '🙏'=>'Prayer', '✝️'=>'Faith', '📖'=>'Bible', '❤️'=>'Care', '🤝'=>'Serving', '👨‍👩‍👧‍👦'=>'Families',
        '🧒'=>'Kids', '🧑‍🤝‍🧑'=>'Community', '☕'=>'Fellowship', '🎵'=>'Music', '🎤'=>'Worship', '🌊'=>'Ocean',
        '🏄'=>'Surfing', '🥋'=>'Jiu Jitsu', '🏃'=>'Fitness', '🍽️'=>'Meals', '🧰'=>'Projects', '🌱'=>'Growth',
        '🕊️'=>'Peace', '🎨'=>'Creative', '🎓'=>'Students', '🔥'=>'Youth', '🚌'=>'Outreach', '🏠'=>'Home Group'
    );
    ob_start(); ?>
    <div class="surfside-staff-shell surfside-information-manager">
      <div class="surfside-staff-back"><a href="<?php echo esc_url(surfside_tools_staff_page_url('site-settings')); ?>">← Back to Site Settings</a></div>
      <section class="surfside-staff-hero"><p class="surfside-staff-eyebrow">Website &amp; App</p><h1>Ministries</h1><p class="surfside-staff-muted">Manage ongoing ministries shared by the website and mobile app. Choose every audience each ministry serves. Bible studies are managed separately through Calendar Manager.</p></section>
      <?php echo $notice; ?>
      <form method="post" class="surfside-information-form">
        <?php wp_nonce_field('surfside_ministries_save','surfside_ministries_nonce'); ?>
        <div class="surfside-information-ministries" data-surfside-ministries>
          <?php foreach($ministries as $index=>$ministry): ?>
          <section class="surfside-information-card surfside-information-ministry">
            <input type="hidden" name="ministries[<?php echo esc_attr($index); ?>][key]" value="<?php echo esc_attr($ministry['key'] ?? ''); ?>">
            <label class="surfside-information-field surfside-ministry-icon-field"><span>Icon</span><span class="surfside-ministry-icon-control"><input type="text" name="ministries[<?php echo esc_attr($index); ?>][icon]" value="<?php echo esc_attr($ministry['icon'] ?? ''); ?>" maxlength="12" placeholder="🙏" data-ministry-icon-input><button type="button" class="surfside-information-remove surfside-ministry-icon-button" data-ministry-icon-open>Choose</button></span></label>
            <label class="surfside-information-field"><span>Ministry name</span><input type="text" name="ministries[<?php echo esc_attr($index); ?>][name]" value="<?php echo esc_attr($ministry['name'] ?? ''); ?>" required></label>
            <label class="surfside-information-field"><span>Usual schedule</span><input type="text" name="ministries[<?php echo esc_attr($index); ?>][schedule]" value="<?php echo esc_attr($ministry['schedule'] ?? ''); ?>"></label>
            <label class="surfside-information-field"><span>Usual location</span><input type="text" name="ministries[<?php echo esc_attr($index); ?>][location]" value="<?php echo esc_attr($ministry['location'] ?? ''); ?>"></label>
            <fieldset class="surfside-ministry-audiences"><legend>Who is this ministry for?</legend><?php foreach($audiences as $key=>$label): ?><label class="surfside-information-checkbox"><input type="checkbox" name="ministries[<?php echo esc_attr($index); ?>][audiences][]" value="<?php echo esc_attr($key); ?>" <?php checked(in_array($key,(array)($ministry['audiences'] ?? array('adults')),true)); ?>> <?php echo esc_html($label); ?></label><?php endforeach; ?></fieldset>
            <label class="surfside-information-field surfside-information-ministry-description"><span>Description</span><textarea name="ministries[<?php echo esc_attr($index); ?>][description]" rows="3"><?php echo esc_textarea($ministry['description'] ?? ''); ?></textarea></label>
            <div class="surfside-information-ministry-actions"><button type="button" class="surfside-information-remove" data-ministry-up>↑</button><button type="button" class="surfside-information-remove" data-ministry-down>↓</button><button type="button" class="surfside-information-remove" data-ministry-remove>Remove</button></div>
          </section>
          <?php endforeach; ?>
        </div>
        <button type="button" class="surfside-information-add" data-ministry-add>+ Add ministry</button>
        <template data-ministry-template><section class="surfside-information-card surfside-information-ministry"><input type="hidden" name="ministries[__INDEX__][key]" value=""><label class="surfside-information-field surfside-ministry-icon-field"><span>Icon</span><span class="surfside-ministry-icon-control"><input type="text" name="ministries[__INDEX__][icon]" maxlength="12" placeholder="🙏" data-ministry-icon-input><button type="button" class="surfside-information-remove surfside-ministry-icon-button" data-ministry-icon-open>Choose</button></span></label><label class="surfside-information-field"><span>Ministry name</span><input type="text" name="ministries[__INDEX__][name]" required></label><label class="surfside-information-field"><span>Usual schedule</span><input type="text" name="ministries[__INDEX__][schedule]"></label><label class="surfside-information-field"><span>Usual location</span><input type="text" name="ministries[__INDEX__][location]"></label><fieldset class="surfside-ministry-audiences"><legend>Who is this ministry for?</legend><?php foreach($audiences as $key=>$label): ?><label class="surfside-information-checkbox"><input type="checkbox" name="ministries[__INDEX__][audiences][]" value="<?php echo esc_attr($key); ?>" <?php checked($key,'adults'); ?>> <?php echo esc_html($label); ?></label><?php endforeach; ?></fieldset><label class="surfside-information-field surfside-information-ministry-description"><span>Description</span><textarea name="ministries[__INDEX__][description]" rows="3"></textarea></label><div class="surfside-information-ministry-actions"><button type="button" class="surfside-information-remove" data-ministry-up>↑</button><button type="button" class="surfside-information-remove" data-ministry-down>↓</button><button type="button" class="surfside-information-remove" data-ministry-remove>Remove</button></div></section></template>
        <div class="surfside-information-actions"><button type="submit" class="surfside-information-save">Save Ministries</button></div>
      </form>
      <div class="surfside-ministry-icon-picker" data-ministry-icon-picker hidden>
        <div class="surfside-ministry-icon-picker-backdrop" data-ministry-icon-close></div>
        <section class="surfside-ministry-icon-picker-panel" role="dialog" aria-modal="true" aria-labelledby="surfside-ministry-icon-title">
          <div class="surfside-ministry-icon-picker-head"><div><p class="surfside-staff-eyebrow">Ministry Icon</p><h2 id="surfside-ministry-icon-title">Choose an emoji</h2><p class="surfside-staff-muted">Pick a common icon below, or close this window and paste any emoji directly into the Icon field.</p></div><button type="button" class="surfside-ministry-icon-close" data-ministry-icon-close aria-label="Close icon picker">×</button></div>
          <div class="surfside-ministry-icon-grid"><?php foreach($icon_choices as $emoji=>$label): ?><button type="button" class="surfside-ministry-icon-choice" data-ministry-icon-value="<?php echo esc_attr($emoji); ?>" title="<?php echo esc_attr($label); ?>"><span aria-hidden="true"><?php echo esc_html($emoji); ?></span><small><?php echo esc_html($label); ?></small></button><?php endforeach; ?></div>
        </section>
      </div>
    </div>
    <style>.surfside-ministry-audiences{grid-column:1/-1;display:flex;gap:14px;flex-wrap:wrap;border:0;padding:0;margin:4px 0}.surfside-ministry-audiences legend{width:100%;font-weight:800;color:#26323d;margin-bottom:5px}.surfside-information-ministry{display:grid;grid-template-columns:150px repeat(3,minmax(0,1fr));gap:12px;align-items:end}.surfside-information-ministry-description,.surfside-information-ministry-actions{grid-column:1/-1}.surfside-information-ministry textarea{box-sizing:border-box;width:100%;padding:10px 12px;border:1px solid #aeb9c4;border-radius:9px;font:inherit}.surfside-information-ministry-actions{display:flex;gap:8px}.surfside-ministry-icon-control{display:grid;grid-template-columns:minmax(56px,1fr) auto;gap:7px;align-items:center}.surfside-ministry-icon-control input{text-align:center;font-size:1.35rem}.surfside-ministry-icon-button{padding-inline:10px}.surfside-ministry-icon-picker[hidden]{display:none}.surfside-ministry-icon-picker{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px}.surfside-ministry-icon-picker-backdrop{position:absolute;inset:0;background:rgba(6,27,51,.55)}.surfside-ministry-icon-picker-panel{position:relative;z-index:1;width:min(720px,100%);max-height:min(760px,90vh);overflow:auto;padding:24px;border-radius:18px;background:#fff;box-shadow:0 24px 70px rgba(6,27,51,.28)}.surfside-ministry-icon-picker-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.surfside-ministry-icon-picker-head h2{margin:0;color:#061b33}.surfside-ministry-icon-close{border:0;background:transparent;color:#52606d;font-size:2rem;line-height:1;cursor:pointer}.surfside-ministry-icon-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.surfside-ministry-icon-choice{display:grid;place-items:center;gap:5px;min-height:84px;padding:9px 6px;border:1px solid #d7e0e8;border-radius:12px;background:#f8fafc;color:#26323d;cursor:pointer}.surfside-ministry-icon-choice:hover,.surfside-ministry-icon-choice:focus-visible{border-color:#0b5fa5;background:#eaf3fb;outline:0}.surfside-ministry-icon-choice span{font-size:1.8rem;line-height:1}.surfside-ministry-icon-choice small{font-size:.73rem;line-height:1.15;text-align:center}@media(max-width:800px){.surfside-information-ministry{grid-template-columns:1fr}.surfside-ministry-icon-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:480px){.surfside-ministry-icon-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}</style>
    <script>(function(){var list=document.querySelector('[data-surfside-ministries]'),add=document.querySelector('[data-ministry-add]'),template=document.querySelector('[data-ministry-template]'),picker=document.querySelector('[data-ministry-icon-picker]'),activeInput=null;if(!list||!add||!template)return;var next=1000;function renumber(){Array.from(list.children).forEach(function(item,i){item.querySelectorAll('[name]').forEach(function(el){el.name=el.name.replace(/ministries\[[^\]]+\]/,'ministries['+i+']');});});}function closePicker(){if(!picker)return;picker.hidden=true;activeInput=null;}add.addEventListener('click',function(){var wrap=document.createElement('div');wrap.innerHTML=template.innerHTML.replaceAll('__INDEX__','new-'+next++).trim();list.appendChild(wrap.firstElementChild);renumber();});list.addEventListener('click',function(e){var item=e.target.closest('.surfside-information-ministry');if(!item)return;if(e.target.closest('[data-ministry-remove]'))item.remove();else if(e.target.closest('[data-ministry-up]')&&item.previousElementSibling)list.insertBefore(item,item.previousElementSibling);else if(e.target.closest('[data-ministry-down]')&&item.nextElementSibling)list.insertBefore(item.nextElementSibling,item);else if(e.target.closest('[data-ministry-icon-open]')){activeInput=item.querySelector('[data-ministry-icon-input]');if(picker)picker.hidden=false;}renumber();});if(picker){picker.addEventListener('click',function(e){var choice=e.target.closest('[data-ministry-icon-value]');if(choice&&activeInput){activeInput.value=choice.getAttribute('data-ministry-icon-value')||'';activeInput.dispatchEvent(new Event('change',{bubbles:true}));closePicker();return;}if(e.target.closest('[data-ministry-icon-close]'))closePicker();});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!picker.hidden)closePicker();});}renumber();})();</script>
    <?php return ob_get_clean();
}
add_shortcode('surfside_staff_ministries_manager','surfside_tools_staff_ministries_manager_shortcode');
