<?php
/** Front-end Mobile App management hub for the Surfside staff dashboard. */
if (!defined('ABSPATH')) { exit; }
function surfside_tools_staff_mobile_app_shortcode(){
 surfside_tools_prevent_cache();surfside_tools_staff_enqueue_styles();if(!is_user_logged_in())return surfside_tools_staff_login_box('Please log in to manage the mobile app.');if(!current_user_can('upload_files'))return '<div class="surfside-staff-shell"><p>You do not have permission to manage the mobile app.</p></div>';
 $cards=array(
  array('title'=>'Home Experience','description'=>'Manage the image and crop used on the app Home screen.','path'=>'mobile-app/home-experience','icon'=>'image','enabled'=>true),
  array('title'=>'Featured Announcement','description'=>'Schedule temporary featured content for the app Home screen.','path'=>'mobile-app/featured-announcement','icon'=>'announcement','enabled'=>true),
  array('title'=>'Push Notifications','description'=>'Send timely updates and service notifications to people using the Surfside app.','path'=>'mobile-app/push-notifications','icon'=>'announcement','enabled'=>true),
 );
 ob_start();?><div class="surfside-staff-shell surfside-mobile-app-management"><div class="surfside-staff-back"><a href="<?php echo esc_url(surfside_tools_staff_page_url(''));?>">← Back to Dashboard</a></div><section class="surfside-staff-hero"><p class="surfside-staff-eyebrow">Mobile App</p><h1>Manage Mobile App</h1><p class="surfside-staff-muted">App-specific presentation and actions for the Surfside mobile experience.</p></section><div class="surfside-staff-grid"><?php foreach($cards as $card):?><article class="surfside-staff-card"><span class="surfside-staff-icon"><?php echo surfside_tools_staff_icon($card['icon']);?></span><h2><?php echo esc_html($card['title']);?></h2><p><?php echo esc_html($card['description']);?></p><div class="surfside-staff-actions"><?php if($card['enabled']):?><a class="surfside-staff-button-secondary" href="<?php echo esc_url(surfside_tools_staff_page_url($card['path']));?>">Open <?php echo esc_html($card['title']);?> <span class="surfside-staff-arrow">›</span></a><?php else:?><span class="surfside-mobile-coming-soon">Coming Later</span><?php endif;?></div></article><?php endforeach;?></div></div><style>.surfside-mobile-coming-soon{display:inline-flex;padding:9px 13px;border-radius:999px;background:#eef4f7;color:#61717d;font-size:13px;font-weight:800}.surfside-mobile-app-management .surfside-staff-card:nth-child(2) h2{white-space:nowrap;font-size:clamp(21px,2vw,25px)}.surfside-mobile-app-management .surfside-staff-card:nth-child(2) .surfside-staff-button-secondary{white-space:nowrap!important;font-size:12.5px!important;padding-left:8px!important;padding-right:8px!important;gap:4px!important;letter-spacing:-.1px}@media(max-width:760px){.surfside-mobile-app-management .surfside-staff-card:nth-child(2) h2,.surfside-mobile-app-management .surfside-staff-card:nth-child(2) .surfside-staff-button-secondary{white-space:normal!important}.surfside-mobile-app-management .surfside-staff-card:nth-child(2) .surfside-staff-button-secondary{font-size:14px!important;padding-left:13px!important;padding-right:13px!important}}</style><?php return ob_get_clean();}
add_shortcode('surfside_staff_mobile_app','surfside_tools_staff_mobile_app_shortcode');
function surfside_tools_ensure_mobile_app_page(){if(!function_exists('surfside_tools_ensure_staff_page'))return;$dashboard=get_page_by_path('dashboard');if(!$dashboard)return;surfside_tools_ensure_staff_page('Manage Mobile App','mobile-app','[surfside_staff_mobile_app]',(int)$dashboard->ID);}add_action('init','surfside_tools_ensure_mobile_app_page',80);
