<?php
/** Public REST API for the Surfside mobile app. */
if (!defined('ABSPATH')) { exit; }
add_action('rest_api_init','surfside_tools_mobile_api_register_routes');
function surfside_tools_mobile_api_register_routes(){
register_rest_route('surfside/v1','/app',array('methods'=>WP_REST_Server::READABLE,'callback'=>'surfside_tools_mobile_api_app','permission_callback'=>'__return_true'));
register_rest_route('surfside/v1','/events',array('methods'=>WP_REST_Server::READABLE,'callback'=>'surfside_tools_mobile_api_events','permission_callback'=>'__return_true','args'=>array('start'=>array('sanitize_callback'=>'sanitize_text_field','validate_callback'=>'surfside_tools_mobile_api_validate_date'),'end'=>array('sanitize_callback'=>'sanitize_text_field','validate_callback'=>'surfside_tools_mobile_api_validate_date'),'limit'=>array('default'=>50,'sanitize_callback'=>'absint','validate_callback'=>function($value){return(int)$value>=1&&(int)$value<=100;}))));
register_rest_route('surfside/v1','/contact',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>'surfside_tools_mobile_api_contact','permission_callback'=>'__return_true'));
}
function surfside_tools_mobile_api_validate_date($value){if($value===null||$value==='')return true;$date=DateTimeImmutable::createFromFormat('!Y-m-d',(string)$value);return $date&&$date->format('Y-m-d')===$value;}
function surfside_tools_mobile_api_app(){
$information=surfside_tools_get_site_information();$identity=(array)($information['identity']??array());$location=(array)($information['location']??array());$streaming=(array)($information['streaming']??array());$announcements=surfside_tools_get_announcements_data();$message=surfside_tools_get_message_data();$message_notes=(string)($message['notes']??'');$message_main_heading=(string)($message['main_heading']??'');$message_notes_html=function_exists('surfside_tools_render_sermon_notes_html')?surfside_tools_render_sermon_notes_html(function_exists('surfside_tools_notes_without_main_heading')?surfside_tools_notes_without_main_heading($message_notes,$message_main_heading):$message_notes):'';$next=function_exists('surfside_tools_watch_live_next_service')?surfside_tools_watch_live_next_service():null;$announcement_video_id=absint($streaming['announcement_video_id']??0);$announcement_video_url=$announcement_video_id?wp_get_attachment_url($announcement_video_id):'';$app_settings=function_exists('surfside_tools_app_settings')?surfside_tools_app_settings():array();$hero_x=max(0,min(100,absint($app_settings['home_hero_focal_x']??50)));$hero_y=max(0,min(100,absint($app_settings['home_hero_focal_y']??50)));$hero_zoom=max(100,min(200,absint($app_settings['home_hero_zoom']??100)));
$payload=array('api_version'=>1,'generated_at'=>current_datetime()->format(DATE_ATOM),'site'=>array('name'=>(string)($identity['name']??''),'tagline'=>(string)($identity['tagline']??''),'logo_url'=>surfside_tools_site_information_logo_url($information),'website_url'=>home_url('/'),'phone'=>(string)($identity['phone']??''),'email'=>sanitize_email($identity['email']??'')),'app'=>array('home_hero_image_url'=>function_exists('surfside_tools_app_hero_image_url')?surfside_tools_app_hero_image_url():'','home_hero_focal_x'=>$hero_x,'home_hero_focal_y'=>$hero_y,'home_hero_zoom'=>$hero_zoom,'giving_url'=>function_exists('surfside_tools_app_giving_url')?surfside_tools_app_giving_url():''),'location'=>array('venue'=>(string)($location['venue']??''),'street'=>(string)($location['street']??''),'city'=>(string)($location['city']??''),'state'=>(string)($location['state']??''),'postal_code'=>(string)($location['postal_code']??''),'address'=>surfside_tools_site_information_address($information),'maps_url'=>surfside_tools_site_information_maps_url($information)),'services'=>array_values(surfside_tools_site_information_services()),'livestream'=>array('twitch_channel'=>sanitize_key($streaming['twitch_channel']??''),'twitch_url'=>!empty($streaming['twitch_channel'])?'https://www.twitch.tv/'.sanitize_key($streaming['twitch_channel']):'','youtube_url'=>surfside_tools_site_information_url($streaming['youtube_url']??''),'facebook_url'=>surfside_tools_site_information_url($streaming['facebook_url']??''),'announcement_video_url'=>$announcement_video_url?esc_url_raw($announcement_video_url):'','next_service'=>surfside_tools_mobile_api_next_service($next)),'announcements'=>array('date'=>(string)($announcements['announcement_date']??''),'items'=>array_values(array_map('strval',(array)($announcements['items']??array()))),'updated_at'=>surfside_tools_mobile_api_timestamp($announcements['timestamp']??0)),'message'=>array('title'=>(string)($message['title']??''),'series'=>(string)($message['series']??''),'date'=>(string)($message['date']??''),'main_heading'=>$message_main_heading,'notes'=>$message_notes,'notes_html'=>wp_kses_post($message_notes_html),'prayer'=>(string)($message['prayer']??''),'updated_at'=>surfside_tools_mobile_api_timestamp($message['timestamp']??0)),'links'=>array('navigation'=>surfside_tools_mobile_api_navigation($information['navigation']??array()),'social'=>surfside_tools_mobile_api_social($information['social']??array())));return rest_ensure_response(apply_filters('surfside_tools_mobile_api_app',$payload));}
function surfside_tools_mobile_api_events(WP_REST_Request $request){$start=$request->get_param('start');$end=$request->get_param('end');$limit=min(100,max(1,absint($request->get_param('limit')?:50)));if(!$start)$start=current_time('Y-m-d');if(!$end)$end=wp_date('Y-m-d',strtotime($start.' +1 year'));if($end<$start)return new WP_Error('surfside_invalid_date_range','The end date must be on or after the start date.',array('status'=>400));$start_date=new DateTimeImmutable($start);$end_date=new DateTimeImmutable($end);if($end_date>$start_date->modify('+2 years'))return new WP_Error('surfside_date_range_too_large','The requested date range cannot exceed two years.',array('status'=>400));$occurrences=surfside_tools_calendar_get_occurrences($start,$end,$limit);$events=array_map('surfside_tools_mobile_api_event',$occurrences);return rest_ensure_response(array('api_version'=>1,'generated_at'=>current_datetime()->format(DATE_ATOM),'range'=>array('start'=>$start,'end'=>$end),'count'=>count($events),'events'=>array_values($events)));}
function surfside_tools_mobile_api_contact(WP_REST_Request $request){
$params=(array)$request->get_json_params();$name=sanitize_text_field($params['name']??'');$email=sanitize_email($params['email']??'');$phone=sanitize_text_field($params['phone']??'');$category=sanitize_key($params['category']??'');$message=sanitize_textarea_field($params['message']??'');$preferred=sanitize_key($params['preferred_contact']??'');$privacy=sanitize_key($params['prayer_privacy']??'');$prayer_name_display=sanitize_key($params['prayer_name_display']??'');$prayer_duration=absint($params['prayer_duration']??0);$website=sanitize_text_field($params['website']??'');
$categories=function_exists('surfside_tools_contact_categories')?surfside_tools_contact_categories():array('general'=>'General Questions','prayer'=>'Prayer Request','ministry'=>'Ministry Information','small-group'=>'Small Group Information','pastor'=>'Speak to a Pastor');$preferred_options=array('email'=>'Email','phone'=>'Phone');$privacy_options=array('prayer-team'=>'Prayer Team','pastoral'=>'Pastoral Staff Only','church-list'=>'Church Prayer List');
if($website!=='')return rest_ensure_response(array('success'=>true,'message'=>'Thank you. Your message has been received.'));
if($name===''||$message===''||!isset($categories[$category]))return new WP_Error('surfside_contact_invalid','Please provide your name, a category, and a message.',array('status'=>400));
if(strlen($message)>2000)return new WP_Error('surfside_contact_too_long','Message cannot exceed 2000 characters.',array('status'=>400));
if($email===''&&$phone==='')return new WP_Error('surfside_contact_method_required','Please provide an email address or phone number.',array('status'=>400));
if(isset($params['email'])&&trim((string)$params['email'])!==''&&!is_email($params['email']))return new WP_Error('surfside_contact_invalid_email','Please provide a valid email address.',array('status'=>400));
if($preferred!==''&&!isset($preferred_options[$preferred]))return new WP_Error('surfside_contact_invalid_preference','Please select a valid preferred contact method.',array('status'=>400));
if($preferred==='email'&&$email==='')return new WP_Error('surfside_contact_email_required','Please provide an email address for email contact.',array('status'=>400));
if($preferred==='phone'&&$phone==='')return new WP_Error('surfside_contact_phone_required','Please provide a phone number for phone contact.',array('status'=>400));
if($category==='prayer'&&$privacy!==''&&!isset($privacy_options[$privacy]))return new WP_Error('surfside_contact_invalid_privacy','Please select a valid prayer privacy option.',array('status'=>400));
if($category==='prayer'&&$privacy==='church-list'&&!in_array($prayer_name_display,array('named','anonymous'),true))return new WP_Error('surfside_contact_invalid_prayer_name','Please choose how your name should appear.',array('status'=>400));
if($category==='prayer'&&$privacy==='church-list'&&!in_array($prayer_duration,array(7,14,30),true))return new WP_Error('surfside_contact_invalid_prayer_duration','Please choose how long your prayer request should remain active.',array('status'=>400));
$ip=$_SERVER['REMOTE_ADDR']??'';$rate_key='surfside_mobile_contact_'.md5($ip?:'unknown');$attempts=(int)get_transient($rate_key);if($attempts>=5)return new WP_Error('surfside_contact_rate_limited','Too many messages have been submitted. Please try again later.',array('status'=>429));set_transient($rate_key,$attempts+1,HOUR_IN_SECONDS);
$to=function_exists('surfside_tools_contact_recipient')?surfside_tools_contact_recipient($category):'';if(!$to){$information=surfside_tools_get_site_information();$identity=(array)($information['identity']??array());$to=sanitize_email($identity['email']??'');}if(!$to)$to=sanitize_email(get_option('admin_email'));if(!$to)return new WP_Error('surfside_contact_unavailable','Contact submissions are temporarily unavailable.',array('status'=>503));
$subject='Surfside App: '.$categories[$category];$lines=array('Name: '.$name,'Email: '.($email?:'Not provided'),'Phone: '.($phone?:'Not provided'),'Category: '.$categories[$category]);if($preferred!=='')$lines[]='Preferred Contact: '.$preferred_options[$preferred];if($category==='prayer'){$lines[]='Prayer Audience: '.($privacy!==''?$privacy_options[$privacy]:'Not specified');if($privacy==='church-list'){$lines[]='Prayer List Name: '.($prayer_name_display==='anonymous'?'Anonymous':'Show name');$lines[]='Requested Active Period: '.$prayer_duration.' days';}}$lines[]='';$lines[]='Message:';$lines[]=$message;$headers=array();if($email)$headers[]='Reply-To: '.$name.' <'.$email.'>';
$sent=wp_mail($to,$subject,implode("\n",$lines),$headers);if(!$sent)return new WP_Error('surfside_contact_send_failed','We could not send your message right now. Please try again later.',array('status'=>500));
if($category==='prayer'&&$privacy==='church-list'&&function_exists('surfside_tools_prayer_list_add_pending'))surfside_tools_prayer_list_add_pending(array('name'=>$name,'email'=>$email,'phone'=>$phone,'message'=>$message,'prayer_name_display'=>$prayer_name_display,'prayer_duration'=>$prayer_duration));
return rest_ensure_response(array('success'=>true,'message'=>'Thank you. Your message has been sent.'));
}
function surfside_tools_mobile_api_event($event){$event_id=absint($event['id']??0);$image_url=$event_id?get_the_post_thumbnail_url($event_id,'large'):'';return array('id'=>$event_id,'title'=>(string)($event['title']??''),'description'=>wp_strip_all_tags((string)($event['description']??''),true),'date'=>(string)($event['date']??''),'end_date'=>(string)($event['end_date']??''),'start_time'=>(string)($event['start_time']??''),'end_time'=>(string)($event['end_time']??''),'all_day'=>!empty($event['all_day']),'featured'=>!empty($event['featured']),'location'=>array('name'=>(string)($event['location_name']??$event['location']??''),'address'=>(string)($event['location_address']??''),'maps_url'=>esc_url_raw($event['location_maps_url']??''),'latitude'=>(string)($event['location_lat']??''),'longitude'=>(string)($event['location_lng']??'')),'image_url'=>$image_url?esc_url_raw($image_url):'');}
function surfside_tools_mobile_api_next_service($next){if(!$next||empty($next['date'])||empty($next['service']))return null;$service=(array)$next['service'];return array('key'=>(string)($service['key']??''),'label'=>(string)($service['label']??''),'starts_at'=>$next['date']->format(DATE_ATOM));}
function surfside_tools_mobile_api_timestamp($timestamp){$timestamp=absint($timestamp);return $timestamp?wp_date(DATE_ATOM,$timestamp):null;}
function surfside_tools_mobile_api_navigation($links){$output=array();foreach((array)$links as $link){$url=surfside_tools_site_information_navigation_url($link);if(!$url)continue;$output[]=array('key'=>sanitize_key($link['key']??''),'label'=>(string)($link['label']??''),'url'=>$url);}return $output;}
function surfside_tools_mobile_api_social($links){$output=array();foreach((array)$links as $key=>$link){$url=surfside_tools_site_information_url($link['url']??'');if(!$url)continue;$output[]=array('key'=>sanitize_key($key),'label'=>(string)($link['label']??ucfirst((string)$key)),'url'=>$url);}return $output;}
