<?php
/** Front-end Mobile App management hub for the Surfside staff dashboard. */
if (!defined('ABSPATH')) { exit; }
function surfside_tools_staff_mobile_app_shortcode(){
 surfside_tools_prevent_cache();surfside_tools_staff_enqueue_styles();if(!is_user_logged_in())return surfside_tools_staff_login_box('Please log in to manage the mobile app.');if(!current_user_can('upload_files'))return '<div class="surfside-staff-shell"><p>You do not have permission to manage the mobile app.</p></div>';
 $cards=array(
  array('title'=>'Home Experience','description'=>'Manage the image and crop used on the app Home screen.','path'=>'mobile-app/home-experience','icon'=>'image','enabled'=>true),
  array('title'=>'Push Notifications','description'=>'Send timely updates and service notifications to people using the Surfside app.','path'=>'','icon'=>'announcement','enabled'=>false),
 );
 ob_start();?><div class="surfside-staff-shell surfside-mobile-app-management"><div class="surfside-staff-back"><a href="<?php echo esc_url(surfside_tools_staff_page_url(''));?>">← Back to Dashboard</a></div><section class="surfside-staff-hero"><p class="surfside-staff-eyebrow">Mobile App</p><h1>Manage Mobile App</h1><p class="surfside-staff-muted">App-specific presentation and actions for the Surfside mobile experience.</p></section><div class="surfside-staff-grid"><?php foreach($cards as $card):?><article class="surfside-staff-card"><span class="surfside-staff-icon"><?php echo surfside_tools_staff_icon($card['icon']);?></span><h2><?php echo esc_html($card['title']);?></h2><p><?php echo esc_html($card['description']);?></p><div class="surfside-staff-actions"><?php if($card['enabled']):?><a class="surfside-staff-button-secondary" href="<?php echo esc_url(surfside_tools_staff_page_url($card['path']));?>">Open <?php echo esc_html($card['title']);?> <span class="surfside-staff-arrow">›</span></a><?php else:?><span class="surfside-mobile-coming-soon">Coming Later</span><?php endif;?></div></article><?php endforeach;?></div></div><style>.surfside-mobile-coming-soon{display:inline-flex;padding:9px 13px;border-radius:999px;background:#eef4f7;color:#61717d;font-size:13px;font-weight:800}</style><?php return ob_get_clean();}
add_shortcode('surfside_staff_mobile_app','surfside_tools_staff_mobile_app_shortcode');
function surfside_tools_ensure_mobile_app_page(){if(!function_exists('surfside_tools_ensure_staff_page'))return;$dashboard=get_page_by_path('dashboard');if(!$dashboard)return;surfside_tools_ensure_staff_page('Manage Mobile App','mobile-app','[surfside_staff_mobile_app]',(int)$dashboard->ID);}add_action('init','surfside_tools_ensure_mobile_app_page',80);
add_filter('do_shortcode_tag',function($output,$tag){if($tag!=='surfside_staff_dashboard'||!is_user_logged_in()||!current_user_can('upload_files'))return $output;$mobile_button='<a class="surfside-staff-button-secondary surfside-mobile-dashboard-action" href="'.esc_url(surfside_tools_staff_page_url('mobile-app')).'">Manage Mobile App <span class="surfside-staff-arrow">›</span></a>';$website_pattern='(<a class="surfside-staff-button"[^>]*>Manage Website <span class="surfside-staff-arrow">›</span></a>)';if(preg_match('~'.$website_pattern.'~',$output)){$mobile_action='<style>.surfside-mobile-dashboard-action{display:flex!important;width:100%!important;box-sizing:border-box;align-items:center;justify-content:center;margin-top:14px!important;text-align:center;text-decoration:none!important;box-shadow:0 8px 20px rgba(15,45,65,.10)!important}</style>'.$mobile_button;return preg_replace('~'.$website_pattern.'~','$1'.$mobile_action,$output,1);}return $output;},10,2);
